### ISSUE TITLE
With composer, there is no way to disable extensions in EM

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#189]
the documentation at https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Extensions/LegacyManagement.html is outdated, see https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html

> Because all extensions present in the system are considered to be active, the Extension Manager UI is adapted to not allow changing the active state of extensions anymore for composer based instances. Respectively the commands extension:activate and extension:deactivate are disabled in Composer managed systems as well.

**Comment by mbrodala** [comment]
You link to the _Legacy Mode_ docs. Here extensions are not installed via Composer. So the docs are still correct:

> All TYPO3 extensions **installed with Composer** are now considered to be active and therefore can and will interact with TYPO3 API.

See https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Extensions/Management.html for the _Composer Mode_ version.
