### ISSUE TITLE
Invalid path in Object Browser tutorial page

### ISSUE THREAD

**Issue by TeNNoX** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#2]
See here:
https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/blob/latest/Documentation/Templates/TheObjectBrowser/Index.rst

It says
> on the image above you can see how the command "**page.10.includeCSS.10** = fileadmin..." is transformed into a tree structure

but in the image, 'includeCSS' is not below 'page.10' in the tree stucture.
So correctly it should be **page.includeCSS.10**, right?

**Comment by marble** [comment]
You're right. I just made the change.
