### ISSUE TITLE
Page Not found Issue

### ISSUE THREAD

**Issue by manoj11patel** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#20]
When going to check system requirements its redirects to "Page Not found"

https://typo3.org/typo3-cms/overview/requirements/

**Comment by sypets** [comment]
Thanks! This is now fixed.

Next time, please post a link of the page where the broken link is found. It helps to quickly resolve the issue. 

In case you are not aware of this, you are also welcome to fix issues like these yourself. Just click on "Edit me on Github" at the top of the page that needs fixing. For more information, see [Contributing to Official Documentation](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html).

**Comment by manojverve** [comment]
Thanks

**Comment by manoj11patel** [comment]
Thanks
