### ISSUE TITLE
Mentioned git project not available in Deployer example

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#204]
https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/DeployTYPO3.html#deployment-automation > 

```php
<?php

namespace Deployer;

require_once(__DIR__ . '/vendor/sourcebroker/deployer-loader/autoload.php');
new \SourceBroker\DeployerExtendedTypo3\Loader();

set('repository', 'git@github.com:sourcebrokergit/t3base10.git');
set('bin/php', '/home/www/example-project-directory/.bin/php');
set('web_path', 'public/');

host('live')
    ->hostname('production.example.org')
    ->user('deploy')
    ->set('branch', 'main')
    ->set('public_urls', ['https://production.example.org'])
    ->set('deploy_path', '/home/www/example-project-directory/live');
```

https://github.com/sourcebrokergit/t3base10 doesn't exist anymore.

**Comment by DavidBruchmann** [comment]
as far as I see, the example code has changed and using now only namespaces (main, v12, v11).
@josefglatz @brotkrueml @linawolf can you confirm that this issue is not relevant anymore and can be closed?

**Comment by linawolf** [comment]
I think we can close this. It is 2 years old and the chapter finally reworked.
