### ISSUE TITLE
Create a new section under Installation that contains information on using third party "performance" tools with TYPO3

### ISSUE THREAD

**Issue by tomwarwick** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#228]
We have an open PR with (useful) information on how to use Redis with TYPO3.

- create a new section within the the installation guide with a meaningful title
- move this new content into this section

Linked to #227

**Comment by sypets** [comment]
@tomwarwick I would appreciate it if you can take care of the structuring and where to put what. You are right, some of my recent PR are more installation / setup related. If I should change my PR to put the content elsewhere please let me know.
