### ISSUE TITLE
There is no 'about page' / update screenshots

### ISSUE THREAD

**Issue by yurigoul** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#23]
The page 'AdvancedClipboard/Index.html' shows content that is not in the tree - I suspect this comes from the old standard content used in older versions of the tutorial

Seen from relase 8.7.20 after installing the Introduction Package

**Comment by sypets** [comment]
Can you add a link or information about how you got there? AdvancedClipboard/Index.rst is not in the master branch or 8.7 branch. https://docs.typo3.org/typo3cms/GettingStartedTutorial/stable/ListModule/AdvancedClipboard/ looks ok to me.

**Comment by yurigoul** [comment]
https://docs.typo3.org/typo3cms/GettingStartedTutorial/ListModule/AdvancedClipboard/Index.html

> Advanced clipboard usage

> Please move to the "TYPO3" page below the "About" page and select one of the "numeric pads":

I have installed the 'official introduction package' using typo3_src-8.7.20. The about page is not in the the official introduction package that came with it

![screen shot 10](https://user-images.githubusercontent.com/11797611/49112723-ca1fdc00-f293-11e8-8b97-00731fea6912.png)
.

**Comment by sypets** [comment]
Ah, now I get it! Of course, that should be corrected. That means, the screenshots on that page would have to be updated too. 

If you can fix that yourself, you are welcome to do that. 

Here are some pointers to get started:
* [Contribute to docs.typo3.org](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html)
* [Images](https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/Images.html)

However, there are still some things to be clarifed. You might want to wait for that. One thing are the images. You will notice, there are text, arrows etc. used in the images. I am working on providing templates / guidelines for that, so we will have a common look and design. But, if you can make the changes there right now, you are welcome to do that.

**Comment by sypets** [comment]
I updated quite a few screenshots for TYPO3 9.5
