### ISSUE TITLE
Address question of opcache settings in "Tuning" section

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#233]
https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/TuneTYPO3.html

Opcache section was moved to "performance tuning" but the section is not so much about (just) performance but mentions some settings which could be problematic if set differently, specifically the opcache.save_comments which must be enabled for Extbase.

Also, the page offers very little for tuning TYPO3.

Initially, the content was moved to this seperate page in order not to clutter up the system requirements page.

Related: #225

**Comment by linawolf** [comment]
The page has been moved to TYPO3 explained. Please open an issue there or - better - make a PR
