### ISSUE TITLE
Document activating / deactivating extensions via CLI without Composer

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#257]
https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Extensions/LegacyManagement.html

`php typo3/sysext/core/bin/typo3`

```
extension:activate
extension:deactivate
```

The commands are not listed currrently, but exist (v11, v12)

See also: 

* changelog (deprecate old commands): 9.4: [Deprecation: #85996 - ExtensionManager CommandController](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.4/Deprecation-85996-ExtensionManagerCommandController.html)
* changelog (deactivated in composer mode): 11.4: ["Feature: #94996 - Consider all Composer installed extensions as active"](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html)
* forge issue (that the commands are not listed): https://forge.typo3.org/issues/99396

**Comment by linawolf** [comment]
Outdated info
