### ISSUE TITLE
Pages not found and unexpected redirect

### ISSUE THREAD

**Issue by cricog** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#261]
The following URL return a 404 instead of displaying their contents.
- https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/BackendPrivileges/Index.html
- https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/BackendUsers/Index.html
- https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/Groups/Index.html
- https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/GroupPermissions/Index.html
- https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/PagePermissions/Index.html
- https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/UserSetup/Index.html

Also, the URL:
https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/UserManagement/Index.html
redirects to:
https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Setup/BackendUsers.html
instead of displaying its content.

**Comment by brotkrueml** [comment]
All URLs are redirected to the recent pages as they were reworked. This is fine and intended.
