### ISSUE TITLE
Missing documentation (v12) for Info Modules

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#300]
### Current behavior

The Info Module for TYPO3 v12 is missing in the documentation. There is no site for it.

### Expected behavior/output

There should be a documentation for the v12 about Info Modules.

### Links

https://docs.typo3.org/m/typo3/tutorial-getting-started/10.4/en-us/OtherBackendModules/InfoAndFunctions/Index.html#info-module

### TYPO3 versions

[12]

### Possible Solution

Finding the maybe already existing page, or If nothing can be found create a new page for the v12 Version (Info Modules)

### Additional context

@wowaTYPO3 helped me to find this problem

**Comment by brotkrueml** [comment]
See also here for the "Localization overview":
https://docs.typo3.org/m/typo3/guide-frontendlocalization/12.4/en-us/LocalizationOverview/Index.html

**Comment by linawolf** [comment]
So I think this can be closed then
