### ISSUE TITLE
TYPO3 9.5 is in composer mode after install / add information about installing intro pkg with composer

### ISSUE THREAD

**Issue by Corvan** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#31]
Hey,

I just tried to follow the Introduction Tutorial and stumbled over the point, that with 9.5 the installed TYPO3 is in composer mode, so the Introduction package has to be installed via `composer require typo3/cms-introduction` So it might be good, giving a hint to that in the Tutorial.

Best regards
Lars

**Comment by sypets** [comment]
@Corvan Yes, thanks for pointing it out, that really should be added. I think you can still do it both ways (install TYPO3 and extensions with or without composer, though composer is the recommended way). 

Do you want to add that yourself? See [Contribute to docs.typo3.org](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html) for more information. 

If not, just let me know and I'll do it.

**Comment by Corvan** [comment]
Hey @sypets, Sorry about the late answer. I thought about adding it, but when I tried to think of how to express this "propely" I got stuck. So if you could do it would be cool and I'll definitely read it to learn how to express this in a way to let newbies like me know how.

**Comment by sypets** [comment]
I see what you mean. I removed the detailed description about installing the Introduction Package and now refer to Installation & Upgrade Guide. That way this part need only be maintained in one manual. The section in Installation & Upgrade Guide already contains clearly separated parts for installing with and without Composer. Please check if this is sufficient and create more issues if necessary.

Additionally, I created https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/issues/59 to maybe improve structure of installing with / without Composer.
