### ISSUE TITLE
Update "getting started tutorial" to current version (9.5+)

### ISSUE THREAD

**Issue by Abdull** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#37]
Currently, the "Getting Started Tutorial" version "latest (9.5)" uses outdated screenshots and descriptions.

This is confusing for TYPO3 newbies such as me and makes onboarding to TYPO3 complicated.

E.g., https://docs.typo3.org/typo3cms/GettingStartedTutorial/GeneralPrinciples/BackendAndFrontend/Index.html has a screenshot `BackendAboutModules.png` which is based on "TYPO3 CMS 7.6.3-dev".

Also, this screenshot shows items in the *module menu* that actually don't exist when following this *getting started tutorial* up to this point.

Statements such as "*It is called the About Modules view and can be reached using the help menu in the top bar* [...]" don't seem to be valid with 9.5: clicking the circled question mark, a drop-down menu appears. But it does not contain an "About Modules" entry.

**Comment by sypets** [comment]
Is mostly updated except for chapter: "User Management". I am still working on that.
