### ISSUE TITLE
tutorial getting started should mention how to get full TYPO3

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#408]
### Current behavior

Right now the tutorial promotes installing TYPO3 using cms-base-distribution. The problem is that it installs just a subset of TYPO3 core extensions. However the user don't know that.
Additionally this differes from the "classic" installation where you have a full TYPO3 out of the box.

### Expected behavior/output

User gets a full TYPO3 when he wants it.

### Links

for the list of missing packages see https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/pull/71/files

### TYPO3 versions

11, 12, 13

**Comment by linawolf** [comment]
You do not need a full installation in starting out. I would mention such posiibilities in TYPO3 Explained.

**Comment by tmotyl** [comment]
please reconsider.
Getting started tutorial is the entry point for people trying TYPO3 for the first time and they expect to see FULL system capabilities, not just a subset.
We should not expect people to read TYPO3 Explained to install and experience the system.

This tutorial is also used by service providers and integrators needing to have working TYPO3 installation but not being TYPO3 experts themselves.

**Comment by linawolf** [comment]
So a new TYPO3 user would need workspaces and indexed-search? Whereever the optional extensions are mentioned we also mention how to install them. Using the `:composer:` directive all you have to do to get the feature you are reading about is copy a `composer req typo3/cms-something` string...

**Comment by tmotyl** [comment]
Yes, a new TYPO3 user needs workspaces and indexed search. New typo3 user doesn't necessarily mean a web-development newbie. TYPO3 is marketed as an enterprise solution and a user who wants to try it out (e.g. to do some due-diligence), should be aware that the command from getting started is not getting him the whole system. 

Do you know any other CMS which doesn't install the full system for you by default?

**Comment by linawolf** [comment]
So this should then be changed by whoever is maintaining `typo3/cms-base-distribution` and not the beginner docs?

**Comment by tmotyl** [comment]
in my pov, in long term either base distribution should be changed, or a new distribution should be introduced e.g. "full distribution".

But for now the documentation should at least mention the fact that not everything is installed, and suggest a command to install missing modules.

**Comment by linawolf** [comment]
Ok, i think there was a tool which helped you to get all packages, let us link there

**Comment by linawolf** [comment]
I added an info box how to get the full installation here: https://docs.typo3.org/m/typo3/tutorial-getting-started/13.4/en-us/Installation/Install.html#install-typo3
