### ISSUE TITLE
Nginx try_files try to serve root directory

### ISSUE THREAD

**Issue by sh3bang** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#411]
Nginx Sample Config seems to be wrong. Requesting root directory and try serving $uri/ will resulting in 403
```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
```

should be
```
location / {
    try_files $uri /index.php$is_args$args;
}
```

https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/SystemRequirements/Index.html

**Comment by linawolf** [comment]
The content was moved here: https://docs.typo3.org/m/typo3/reference-coreapi/13.4/en-us/Administration/Installation/SystemRequirements/Index.html# Please make a PR or issue there
