### ISSUE TITLE
Improve introduction into Fluid

### ISSUE THREAD

**Issue by mkiebele** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#435]
We need a beginner friendly description about theming in TYPO3 and an introduction in fluid for the new "getting started" tutorial. 

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fluid/Introduction.html

**Comment by linawolf** [comment]
I moved the Fluid introduction from the site package tutorial here.

It still needs to be greately improved though.
