### ISSUE TITLE
Update Next Steps in getting started

### ISSUE THREAD

**Issue by mkiebele** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#452]
Possible topics:

- Deployment https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/DeployTYPO3.html
- Unit / Functional Testing https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/Index.html
- Static code analysis https://usetypo3.com/code-analysis/
- CGL https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/CodingGuidelines/Index.html
- RTE configuration, HTML Parsing https://daniel-siepmann.de/typo3-rte-for-input-fields.html
- Backend user / Permissions 
- Multilanguage handling
- Multi site handling
- Contributing https://typo3.org/community/contribute

**Comment by linawolf** [comment]
Have a look a this chapter and see what can be improved; https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/NextSteps/Index.html
