### ISSUE TITLE
Problem on https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us//FirstProject/IntroductionPackage/Index.html

### ISSUE THREAD

**Issue by SteffN82** [TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted#546]
Error message after second step (vendor/bin/typo3 extension:setup):

Uncaught TYPO3 Exception #2002: An exception occurred in the driver: Connection refused
thrown in file /html/typo3-composer/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php
in line 101

Result: no pre-built pages within the page tree

created in a freshly installed TYPO3, Version 13.4.0

**Comment by linawolf** [comment]
This sounds like the database cannot be reached. Does database compare work in the install tool?
